/* eslint-disable @next/next/no-img-element */
import { BRAND_LOGO_SRC, OPENING_BRAND_COPY, RELATION_NOTES, overviewCards } from './guided-story-data';
import { EdgeLayer, FlowBoard, OverviewGrid, RelationBadge, RelationRail, COMPLETE_FOCUS, EMPTY_FOCUS, cx } from './guided-story-shared';
import type { BadgeMap, CardRefs, LayoutMap, SceneRootRef, StorySceneState } from './guided-story-types';
import styles from './home-onboarding-preview.module.sass';

export function GuidedStoryScenes({ state, layouts, badges, cardRefs, setRootRef }: { state: StorySceneState; layouts: LayoutMap; badges: BadgeMap; cardRefs: CardRefs; setRootRef: SceneRootRef }) {
  const s = state;
  return (
    <>
      <section className={cx(styles.scene, s.chapterIndex === 0 && styles.active)} data-scene="0"><div className={cx(styles.sceneInner, styles.openingLayout)}><div className={cx(styles.openingBrand, s.openingReady && styles.isReady)}><img src={BRAND_LOGO_SRC} alt="TMD Construtor" width={1108} height={262} /><p>{OPENING_BRAND_COPY}</p></div></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 1 && styles.active)} data-scene="1"><div className={styles.sceneInner}><div ref={setRootRef('overview')} className={styles.overviewWrap}><EdgeLayer sceneKey="overview" layout={layouts.overview} local={0} keep={false} startsByGroup={[0, 0, 0]} duration={1} stagger={0} /><OverviewGrid idPrefix="overview" cardRefs={cardRefs} focus={s.overviewFlags} /></div></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 2 && styles.active)} data-scene="2"><div className={styles.sceneInner}><div ref={setRootRef('relations')} className={styles.overviewWrap}><EdgeLayer sceneKey="relations" layout={layouts.relations} local={s.relationsEdgeLocal} keep={false} startsByGroup={[900, 4800, 8700]} duration={1850} stagger={0} /><RelationBadge kind="risk" active={s.relationsRiskActive} pos={badges.relations?.risk} /><RelationBadge kind="hyp" active={s.relationsHypActive} pos={badges.relations?.hyp} /><OverviewGrid idPrefix="relations" cardRefs={cardRefs} focus={overviewCards.map(() => COMPLETE_FOCUS)} /></div><RelationRail notes={RELATION_NOTES.relations} riskActive={s.relationsRiskNote} hypActive={s.relationsHypNote} /></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 3 && styles.active)} data-scene="3"><div className={styles.sceneInner}><div className={styles.detailWrap}><FlowBoard idPrefix="structure" cardRefs={cardRefs} columnFocus={s.structureFlags} cardFocus={Array.from({ length: 12 }, () => EMPTY_FOCUS)} /></div></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 4 && styles.active)} data-scene="4"><div className={styles.sceneInner}><div className={styles.detailWrap}><FlowBoard idPrefix="details" cardRefs={cardRefs} columnFocus={s.detailsState.columns} cardFocus={s.detailsState.cards} /></div></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 5 && styles.active)} data-scene="5"><div className={styles.sceneInner}><div ref={setRootRef('causality')} className={cx(styles.detailWrap, styles.detailWrapCausality)}><EdgeLayer sceneKey="causality" layout={layouts.causality} local={s.causalityEdgeLocal} keep={false} startsByGroup={[900, 6100, 11300]} duration={1800} stagger={220} /><RelationBadge kind="risk" active={s.causalityRiskActive} pos={badges.causality?.risk} /><RelationBadge kind="hyp" active={s.causalityHypActive} pos={badges.causality?.hyp} /><FlowBoard idPrefix="causality" cardRefs={cardRefs} columnFocus={s.allCompleteColumns} cardFocus={s.allCompleteCards} compact /></div><RelationRail notes={RELATION_NOTES.causality} riskActive={s.causalityRiskNote} hypActive={s.causalityHypNote} /></div></section>
      <section className={cx(styles.scene, s.chapterIndex === 6 && styles.active)} data-scene="6"><div className={styles.sceneInner}><div ref={setRootRef('final')} className={cx(styles.detailWrap, styles.detailWrapCausality)}><EdgeLayer sceneKey="final" layout={layouts.final} local={s.finalEdgeLocal} keep startsByGroup={[0, 0, 0]} duration={1} stagger={0} /><RelationBadge kind="risk" active={s.showFinalComplete} pos={badges.final?.risk} /><RelationBadge kind="hyp" active={s.showFinalComplete} pos={badges.final?.hyp} /><FlowBoard idPrefix="final" cardRefs={cardRefs} columnFocus={s.allCompleteColumns} cardFocus={s.allCompleteCards} compact /></div></div></section>
    </>
  );
}
